language: python
python:
  - "3.5.1"
install:
  # Build/test dependencies
  - pip install -r requirements.txt
script:
  # Normal tests
  - py.test
after_success:
  - bash <(curl -s https://codecov.io/bash)
